name: Deploy to Dev

permissions:
  id-token: write   # Allow assume IAM Role via GitHub OIDC
  contents: read    # This is required for actions/checkout@v2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: ukraine-taskforce/update-s3-frontend-action@v0.0.1
        with:
          aws-region: eu-central-1
          node-version: 14.x
          role-arn: ${{ secrets.DEPLOY_ROLE_ARN }}
          s3-bucket: ${{ secrets.S3_URL }}
