name: Deploy to Prod S3
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_URL: ${{ secrets.PROD_S3_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: eu-central-1
      - run: yarn s3p sync -y -t $S3_URL
